import sys
sys.path.insert(0, ".")
sys.stdout.reconfigure(encoding='utf-8')

from datetime import datetime
from sqlmodel import Session, select
from app.database import engine, init_db
from app.models import JobStatus, Stream, VTuber

failed_entries = [
    ('Shiori Novella', 'UkqwIcO3YN8', 'Weekly Tentative Schedule', 'Scheduled Live Stream (Upcoming event in 265 days)'),
    ('Shiori Novella', 'WnBExtoUM5o', 'Making My Ideal Husbando with Random Body Parts 【Eronoctosis】', 'Scheduled Live Stream (Upcoming broadcast)'),
    ('Nerissa Ravencroft', 'Criw5zhE0bI', '🐦‍⬛ JAILBIRD FREE CHAT🎼', 'Scheduled Free Chat (Captions pending stream broadcast)'),
    ('Nerissa Ravencroft', 'roWaAwUYqFI', 'So many fun things have been happening~ | Members-Only', 'Members-Only Stream (YouTube captions gated behind channel membership login)'),
    ('Vestia Zeta', '38fJIy2FoDg', '𝐂𝐀𝐓𝐋𝐎𝐑𝐃', 'Short Teaser Premiere (No caption track generated by YouTube)'),
    ('Vestia Zeta', 'W2cPwFpX8DE', '【Road to Empress II】ABSOLUTE CINEMA? ※Spoilers', 'Pending YouTube Auto-Caption Processing (3.3-hour VOD captions currently processing)'),
]

print("=== Seeding Failed Stream Log Records into Database ===")
init_db()

with Session(engine) as session:
    for name, vid, title, error_msg in failed_entries:
        existing = session.exec(select(Stream).where(Stream.video_id == vid)).first()
        if not existing:
            vtuber = session.exec(select(VTuber).where(VTuber.name == name)).first()
            stream = Stream(
                video_id=vid,
                title=title,
                duration_seconds=0,
                published_at=datetime.utcnow(),
                thumbnail_url=f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
                status=JobStatus.FAILED,
                error_message=error_msg,
                vtuber_id=vtuber.id if vtuber else None
            )
            session.add(stream)
            print(f"   ➕ Added failed stream record: '{title}' ({vid})")
        else:
            print(f"   ℹ️ Stream record already exists: '{title}' ({vid})")
    session.commit()
    print("✓ Finished seeding failed stream records.")
